# Generated by Django 2.2.1 on 2019-07-08 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice_board', '0002_dograting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DogRating',
            new_name='PetRating',
        ),
    ]
