# Generated by Django 2.2.1 on 2019-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0003_auto_20190708_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_kind',
            field=models.CharField(default='Pet', max_length=4),
            preserve_default=False,
        ),
    ]
